
defaults:
  - dataset: replica # Choice of dataset
  - mode: train # "train" or "test"
  - model: unet_baseline # Choice of model
  - _self_


# Hydra settings
hydra:
    run:
        dir: outputs/${model.name}_configs/${dataset.name}/${mode.mode}_${mode.experiment_name}/${now:%H-%M-%S}
    output_subdir: configfile
    


