# Training Settings
mode: train
experiment_name: diffusion_test_wav3 # Name of the experiment

checkpoints: null # Checkpoints to resume training
saving_checkpoints: 10 # Save model every "saving_checkpoints" epochs
epochs: 200 # Number of training epochs
learning_rate: 0.0001 # Learning rate
optimizer: AdamW # Optimize: 'Adam' or 'AdamW' or 'SGD' available
criterion: L1 # Loss 

validation: True # Perform validation 
validation_iter: 2 # Evaluate model on validation every "validation_iter" epochs
validation_display: 10 # Display validation images every "validation_display" epochs

print_tensorboard: 50 # Display train images every "print_tensorboard" epochs

num_threads: 4
batch_size: 8
shuffle: True # If "True" shuffle train set 

#multirun: True # If "True" will adapt experiment name to choice of parameters. Allow grid search with hydra.